# Generated by Django 4.2.4 on 2023-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
