# Generated by Django 4.2.4 on 2023-10-21 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_input_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='bookmark',
            field=models.ManyToManyField(blank=True, null=True, related_name='inputBookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
