# Generated by Django 4.2.4 on 2023-10-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_alter_input_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='input',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='input',
            name='url',
        ),
    ]
