# Generated by Django 4.2.4 on 2023-10-22 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSite', to=settings.AUTH_USER_MODEL),
        ),
    ]
