# Generated by Django 4.2.4 on 2023-10-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_site_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorySite', to='capstone.category'),
        ),
        migrations.AddField(
            model_name='site',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputSite', to='capstone.input'),
        ),
    ]
